name: workflow

on:
  push:
     branches:
       - main
     paths-ignore:
        - 'README.md'
permission:
   id-taken: writes
   contents: read

jobs:
   integration:
       name: Continuous Integration
       runs on: ubuntu-latest
       steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Lint code
          run: echo "Linking repository"

        - name: Run unit test
          run:  echo "Running unit tests"
    
    build-and-push-ecr-image:
       name: Continuous Delivery
       needs: integration
       runs-on: ubuntu-latest


